before_script: 
 - sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"  
script: nanobox run mix test  
after_script:  
  - nanobox remote add nanobox_phoenix_phoenix
  - nanobox deploy

